/*     */ package cpw.mods.fml.common;
/*     */ 
/*     */ import com.google.common.base.Throwables;
/*     */ import com.google.common.collect.Maps;
/*     */ import com.google.gson.Gson;
/*     */ import com.google.gson.GsonBuilder;
/*     */ import com.google.gson.JsonArray;
/*     */ import com.google.gson.JsonElement;
/*     */ import com.google.gson.JsonParseException;
/*     */ import com.google.gson.JsonParser;
/*     */ import com.google.gson.TypeAdapter;
/*     */ import com.google.gson.stream.JsonReader;
/*     */ import com.google.gson.stream.JsonWriter;
/*     */ import cpw.mods.fml.common.versioning.ArtifactVersion;
/*     */ import cpw.mods.fml.common.versioning.VersionParser;
/*     */ import java.io.IOException;
/*     */ import java.io.InputStream;
/*     */ import java.io.InputStreamReader;
/*     */ import java.util.Map;
/*     */ import org.apache.logging.log4j.Level;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public class MetadataCollection
/*     */ {
/*     */   private String modListVersion;
/*     */   private ModMetadata[] modList;
/*  40 */   private Map<String, ModMetadata> metadatas = Maps.newHashMap();
/*     */ 
/*     */   
/*     */   public static MetadataCollection from(InputStream inputStream, String sourceName) {
/*  44 */     if (inputStream == null)
/*     */     {
/*  46 */       return new MetadataCollection();
/*     */     }
/*     */     
/*  49 */     InputStreamReader reader = new InputStreamReader(inputStream);
/*     */     
/*     */     try {
/*     */       MetadataCollection collection;
/*  53 */       Gson gson = (new GsonBuilder()).registerTypeAdapter(ArtifactVersion.class, new ArtifactVersionAdapter()).create();
/*  54 */       JsonParser parser = new JsonParser();
/*  55 */       JsonElement rootElement = parser.parse(reader);
/*  56 */       if (rootElement.isJsonArray()) {
/*     */         
/*  58 */         collection = new MetadataCollection();
/*  59 */         JsonArray jsonList = rootElement.getAsJsonArray();
/*  60 */         collection.modList = new ModMetadata[jsonList.size()];
/*  61 */         int i = 0;
/*  62 */         for (JsonElement mod : jsonList)
/*     */         {
/*  64 */           collection.modList[i++] = (ModMetadata)gson.fromJson(mod, ModMetadata.class);
/*     */         }
/*     */       }
/*     */       else {
/*     */         
/*  69 */         collection = (MetadataCollection)gson.fromJson(rootElement, MetadataCollection.class);
/*     */       } 
/*  71 */       collection.parseModMetadataList();
/*  72 */       return collection;
/*     */     }
/*  74 */     catch (JsonParseException e) {
/*     */       
/*  76 */       FMLLog.log(Level.ERROR, (Throwable)e, "The mcmod.info file in %s cannot be parsed as valid JSON. It will be ignored", new Object[] { sourceName });
/*  77 */       return new MetadataCollection();
/*     */     }
/*  79 */     catch (Exception e) {
/*     */       
/*  81 */       throw Throwables.propagate(e);
/*     */     } 
/*     */   }
/*     */ 
/*     */ 
/*     */   
/*     */   private void parseModMetadataList() {
/*  88 */     for (ModMetadata modMetadata : this.modList)
/*     */     {
/*  90 */       this.metadatas.put(modMetadata.modId, modMetadata);
/*     */     }
/*     */   }
/*     */ 
/*     */   
/*     */   public ModMetadata getMetadataForId(String modId, Map<String, Object> extraData) {
/*  96 */     if (!this.metadatas.containsKey(modId)) {
/*     */       
/*  98 */       ModMetadata dummy = new ModMetadata();
/*  99 */       dummy.modId = modId;
/* 100 */       dummy.name = (String)extraData.get("name");
/* 101 */       dummy.version = (String)extraData.get("version");
/* 102 */       dummy.autogenerated = true;
/* 103 */       this.metadatas.put(modId, dummy);
/*     */     } 
/* 105 */     return this.metadatas.get(modId);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public static class ArtifactVersionAdapter
/*     */     extends TypeAdapter<ArtifactVersion>
/*     */   {
/*     */     public void write(JsonWriter out, ArtifactVersion value) throws IOException {}
/*     */ 
/*     */ 
/*     */ 
/*     */     
/*     */     public ArtifactVersion read(JsonReader in) throws IOException {
/* 120 */       return VersionParser.parseVersionReference(in.nextString());
/*     */     }
/*     */   }
/*     */ }


/* Location:              D:\WorkTools\Project\Minecraft\plugins\craftbukkit\1.7.10\CValue\libs\core\forgeSrc-1.7.10-10.13.4.1614-1.7.10.jar!\cpw\mods\fml\common\MetadataCollection.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */