/*    */ package cpw.mods.fml.common;
/*    */ 
/*    */ import com.google.common.base.Function;
/*    */ import com.google.common.base.Joiner;
/*    */ import com.google.common.collect.Lists;
/*    */ import com.google.common.collect.Sets;
/*    */ import com.google.gson.annotations.SerializedName;
/*    */ import cpw.mods.fml.common.functions.ModNameFunction;
/*    */ import cpw.mods.fml.common.versioning.ArtifactVersion;
/*    */ import java.util.List;
/*    */ import java.util.Set;
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ public class ModMetadata
/*    */ {
/*    */   @SerializedName("modid")
/*    */   public String modId;
/*    */   public String name;
/* 35 */   public String description = "";
/*    */   
/* 37 */   public String url = "";
/* 38 */   public String updateUrl = "";
/*    */   
/* 40 */   public String logoFile = "";
/* 41 */   public String version = "";
/* 42 */   public List<String> authorList = Lists.newArrayList();
/* 43 */   public String credits = "";
/* 44 */   public String parent = "";
/*    */   
/*    */   public String[] screenshots;
/*    */   
/*    */   public transient ModContainer parentMod;
/*    */   
/* 50 */   public transient List<ModContainer> childMods = Lists.newArrayList();
/*    */   
/*    */   public boolean useDependencyInformation;
/* 53 */   public Set<ArtifactVersion> requiredMods = Sets.newHashSet();
/* 54 */   public List<ArtifactVersion> dependencies = Lists.newArrayList();
/* 55 */   public List<ArtifactVersion> dependants = Lists.newArrayList();
/*    */ 
/*    */ 
/*    */   
/*    */   public transient boolean autogenerated;
/*    */ 
/*    */ 
/*    */ 
/*    */   
/*    */   public String getChildModCountString() {
/* 65 */     return String.format("%d child mod%s", new Object[] { Integer.valueOf(this.childMods.size()), (this.childMods.size() != 1) ? "s" : "" });
/*    */   }
/*    */ 
/*    */   
/*    */   public String getAuthorList() {
/* 70 */     return Joiner.on(", ").join(this.authorList);
/*    */   }
/*    */ 
/*    */   
/*    */   public String getChildModList() {
/* 75 */     return Joiner.on(", ").join(Lists.transform(this.childMods, (Function)new ModNameFunction()));
/*    */   }
/*    */ 
/*    */   
/*    */   public String printableSortingRules() {
/* 80 */     return "";
/*    */   }
/*    */ }


/* Location:              D:\WorkTools\Project\Minecraft\plugins\craftbukkit\1.7.10\CValue\libs\core\forgeSrc-1.7.10-10.13.4.1614-1.7.10.jar!\cpw\mods\fml\common\ModMetadata.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */